sudo sh ./library/zsh-makeup.sh
sudo sh ./library/hosting-tools-set.sh
sudo sh ./library/brew-install.sh
sudo sh ./library/nvm-install.sh
sudo sh ./library/font-install.sh
sudo sh ./library/python-install.sh
sudo sh ./library/https-injection.sh
sudo sh ./library/language-set.sh
sudo sh ./library/anaconda-install.sh
sudo sh ./library/mysql-install.sh
sudo sh ./library/mongodb-install.sh
