from typing import Optional
from dtos.baseDto import BaseDtoMixin


class ObserveDto(BaseDtoMixin):
    def __init__(self, **data):
        super().__init__(**data)

    area: str = ...
    camPort: str = ...
    activate: bool = ...
    alarms: str = ...
    date: str = ...
    computeDevice: str = ...
    savingPath: str = ...
    camName: str = ...
    sensingModel: str = ...
    camCoordinate1: str = ...
    camCoordinate2: str = ...
    camSafetyLevel1: str = ...
    camSafetyLevel2: str = ...
    camSensing1: Optional[int] = None
    camSensing2: Optional[int] = None