from typing import Optional
from dtos.baseDto import BaseDtoMixin


class TrackerDto(BaseDtoMixin):
    def __init__(self, **data):
        super().__init__(**data)

    ip: str = ...
    area: str = ...
    camPort: str = ...
    camName: str = ...
    computeDevice: str = ...
    savingPath: str = ...
    sensingModel: str = ...
    calibImg: str = ...
    baseLine: str = ...
    dangerLine: str = ...
    sensingGroup1: Optional[str] = None
    sensingGroup2: Optional[str] = None
    threshold: int = ...
    imgSaveSwitch: bool = ...
    messageSwitch: bool = ...
    kakaoSwitch: bool = ...


