export const initVideoFrameData: Array<ViedeoFrameType> = [
  {
    ip: '',
    canvasClass: 'polygonCanvas1',
    frameSrc: '',
    trackerId: '',
    baseLine: '',
    dangerLine: '',
    camName: '',
    firstCanvas: {
      visible: false,
      yellowSensingPercent: 1.37,
      redSensingPercent: 0.3,
      coordinate: [
        // [185, 236],
        // [90, 93],
        // [186, 109],
        // [268, 203],
      ],
    },
    secondCanvas: {
      visible: false,
      yellowSensingPercent: 0.7,
      redSensingPercent: 0.3,
      coordinate: [
        // [185, 236],
        // [90, 93],
        // [186, 109],
        // [268, 203],
      ],
    },
  },
  {
    ip: '',
    canvasClass: 'polygonCanvas2',
    frameSrc: '',
    trackerId: '',
    baseLine: '',
    camName: '',
    dangerLine: '',
    firstCanvas: {
      visible: false,
      yellowSensingPercent: 0.7,
      redSensingPercent: 0.3,
      coordinate: [
        // [242, 122],
        // [298, 139],
        // [296, 189],
        // [239, 191],
      ],
    },
    secondCanvas: {
      visible: false,
      yellowSensingPercent: 0.7,
      redSensingPercent: 0.3,
      coordinate: [],
    },
  },
  {
    ip: '',
    canvasClass: 'polygonCanvas3',
    frameSrc: '',
    trackerId: '',
    baseLine: '',
    camName: '',
    dangerLine: '',
    firstCanvas: {
      visible: false,
      yellowSensingPercent: 0.7,
      redSensingPercent: 0.3,
      coordinate: [],
    },
    secondCanvas: {
      visible: false,
      yellowSensingPercent: 0.7,
      redSensingPercent: 0.3,
      coordinate: [],
    },
  },
  {
    ip: '',
    canvasClass: 'polygonCanvas4',
    frameSrc: '',
    trackerId: '',
    baseLine: '',
    camName: '',
    dangerLine: '',
    firstCanvas: {
      visible: false,
      yellowSensingPercent: 0.7,
      redSensingPercent: 0.3,
      coordinate: [],
    },
    secondCanvas: {
      visible: false,
      yellowSensingPercent: 0.7,
      redSensingPercent: 0.3,
      coordinate: [],
    },
  },
];
